/*
 * payment.java
 *
 * Created on December 12, 2016, 12:31 PM
 */

package aitec1;

import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import java.sql.Connection;
import java.sql.ResultSet;

import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  User
 */
public class add_course extends javax.swing.JFrame {

    /** Creates new form payment */
    public add_course() {
        initComponents();

 txtduration.setText("");
        txtfee1.setText("");
        txtname.setText("");
        txtlec.setText("");
        /*    try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
            String newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
            
            lbldate.setText(newdate);
           // jLabel2.setText(ar[3]); 
                    }
                
                }
            }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       */ 
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtduration = new javax.swing.JTextField();
        txtfee1 = new javax.swing.JTextField();
        txtlec = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 110, 60));

        jLabel12.setFont(new java.awt.Font("Aparajita", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("AiTEC");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 110, 60));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ho.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 110, 60));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 120, 60));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 120, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Course Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Duration");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Course Fee");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Lecturer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtname.setText("jTextField1");
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 170, -1));

        txtduration.setText("jTextField1");
        jPanel1.add(txtduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, -1));

        txtfee1.setText("jTextField1");
        jPanel1.add(txtfee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, -1));

        txtlec.setText("jTextField1");
        jPanel1.add(txtlec, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 320, 200));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADD NEW COURSE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 650));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-846)/2, (screenSize.height-670)/2, 846, 670);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
     
    try {
        
        Connection c=DB.mycon();
        Statement s=c.createStatement();
       int x= JOptionPane.showConfirmDialog(rootPane, "Do you want to save this record");
        if(x==0){

   

        s.executeUpdate("INSERT INTO course(name,duration,fee,lec) VALUES('"+txtname.getText()+"','"+txtduration.getText()+"','"+txtfee1.getText()+"','"+txtlec.getText()+"')");
        txtduration.setText("");
        txtfee1.setText("");
        txtname.setText("");
         txtlec.setText("");
    
        }
        else if(x==1){
            txtduration.setText("");
        txtfee1.setText("");
        txtname.setText("");
        txtlec.setText("");
   
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    try {
         Connection c=DB.mycon();
        Statement s=c.createStatement();
        ResultSet rs=s.executeQuery("SELECT * FROM course WHERE name='"+txtname.getText()+"'");
        while(rs.next()){
            txtname.setText(rs.getString("name"));
            txtfee1.setText(rs.getString("fee"));
            txtduration.setText(rs.getString("duration"));
            txtlec.setText(rs.getString("lec"));
        

        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    
     try {
            
        Connection c=DB.mycon();
        Statement s=c.createStatement();
       int x= JOptionPane.showConfirmDialog(rootPane, "Do you want to Update this record");
        if(x==0){

   

        s.executeUpdate("UPDATE course SET fee='"+txtfee1.getText()+"',lec='"+txtlec.getText()+"',duration='"+txtduration.getText()+"' WHERE name='"+txtname.getText()+"'");
       
     txtduration.setText("");
        txtfee1.setText("");
        txtname.setText("");
       txtlec.setText("");
        }
        else if(x==1){
        txtduration.setText("");
        txtfee1.setText("");
        txtname.setText("");
        txtlec.setText("");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    
     try {
            
        Connection c=DB.mycon();
        Statement s=c.createStatement();
       int x= JOptionPane.showConfirmDialog(rootPane, "Do you want to Update this record");
        if(x==0){

   

        s.executeUpdate("DELETE FROM course WHERE name='"+txtname.getText()+"'");
       
     txtduration.setText("");
        txtfee1.setText("");
        txtname.setText("");
     txtlec.setText("");
        }
        else if(x==1){
        txtduration.setText("");
        txtfee1.setText("");
        txtname.setText("");
       txtlec.setText("");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  try {
                    UIManager.setLookAndFeel(new GraphiteLookAndFeel());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new add_course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtduration;
    private javax.swing.JTextField txtfee1;
    private javax.swing.JTextField txtlec;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
