/*
 * payment.java
 *
 * Created on December 12, 2016, 12:31 PM
 */

package aitec1;

import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import java.sql.Connection;
import java.sql.ResultSet;

import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  User
 */
public class addToNewCourse extends javax.swing.JFrame {

    /** Creates new form payment */
    public addToNewCourse() {
        initComponents();

           txtname.setText("");
           
            txt2id.setText("");
            txt2payment.setText("");
            c2course.setSelectedIndex(0);
            try {
            
                       Connection c=DB.mycon();
            Statement s=c.createStatement();
            ResultSet rs=s.executeQuery("SELECT * FROM `course` WHERE 1");
            
            while(rs.next()){
            
                c2course.addItem(rs.getString("name"));
            
            }
                
        } catch (Exception e) {
            e.printStackTrace();
        }
            
                 try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
            String newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
            
            lbldate.setText(newdate);
           
           // jLabel2.setText(ar[3]); 
                    }
                
                }
            }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
     

        /*    try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
            String newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
            
            lbldate.setText(newdate);
           // jLabel2.setText(ar[3]); 
                    }
                
                }
            }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       */ 
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt2payment = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txt2id = new javax.swing.JTextField();
        c2course = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbldate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Aparajita", 1, 36));
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("AiTEC");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 110, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel14.setText("Payment :  RS :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setText("Student Name : ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel16.setText("Student ID : ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel17.setText("Course : ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        txt2payment.setText("jTextField1");
        jPanel2.add(txt2payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, 30));

        txtname.setText("jTextField1");
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 200, 30));

        txt2id.setText("txt2id");
        txt2id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2idActionPerformed(evt);
            }
        });
        jPanel2.add(txt2id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 200, 30));

        c2course.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Course" }));
        c2course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2courseActionPerformed(evt);
            }
        });
        jPanel2.add(c2course, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 200, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 730, 210));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ho.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 110, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD STUDENT TO NEW COURSE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 110, 60));

        lbldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1.jpg"))); // NOI18N
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 650));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-846)/2, (screenSize.height-670)/2, 846, 670);
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    
    try {
        
        int y=JOptionPane.showConfirmDialog(rootPane, "Do yo want to add yhis Payment???");
        
        if(y==0){
            Connection c=DB.mycon();
            Statement s=c.createStatement();
            s.executeUpdate("INSERT INTO `payment`(`sid`, `name`, `course`, `amount`, `datet`) VALUES (  '"+txt2id.getText()+"','"+txtname.getText()+"','"+c2course.getSelectedItem().toString()+"','"+txt2payment.getText()+"','"+lbldate.getText()+"')");
          
           
            JOptionPane.showMessageDialog(rootPane, "New Student Enrolled..");
            
           
            txtname.setText("");
            txt2id.setText("");
            txt2payment.setText("");
            c2course.setSelectedIndex(0);
            
            
        
        }
        else if(y==1){
        
              
            txtname.setText("");
            txt2id.setText("");
            txt2payment.setText("");
            c2course.setSelectedIndex(0);
            
        }
        
    } catch (Exception e) {
     e.printStackTrace();
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void txt2idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2idActionPerformed
// TODO add your handling code here:
    
    try {
        
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        
        ResultSet re=s.executeQuery("SELECT * FROM students WHERE sid='"+txt2id.getText()+"'");
        
        while(re.next()){
        
            txtname.setText(re.getString("name"));
        }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txt2idActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    
           txtname.setText("");
            txt2id.setText("");
            txt2payment.setText("");
            c2course.setSelectedIndex(0);
}//GEN-LAST:event_jButton1ActionPerformed

private void c2courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2courseActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_c2courseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  try {
                    UIManager.setLookAndFeel(new GraphiteLookAndFeel());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new addToNewCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c2course;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JTextField txt2id;
    private javax.swing.JTextField txt2payment;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
