/*
 * payment.java
 *
 * Created on December 12, 2016, 12:31 PM
 */

package aitec1;

import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import java.sql.Connection;
import java.sql.ResultSet;

import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  User
 */
public class paymentHome extends javax.swing.JFrame {

    /** Creates new form payment */
    public paymentHome() {
        initComponents();
        
          txtadm.setText("");
        txtam.setText("");
        txtid.setText("");
        txtname.setText("");
         lbldue.setText("RS : 0.00");
          lbltotalpay.setText("RS : 0.00");
        lblcourse.setText("JAVA");
           txtaf.setText("");
        txtamount.setText("");
        txtaid.setText("");
        txtaname.setText("");
         lbla2.setText("RS : 0.00");
          lbla3.setText("RS : 0.00");
        lbla1.setText("ANDROID");
            txtpf.setText("");
        txtptotal.setText("");
        txtpid.setText("");
        txtpname.setText("");
         lblp2.setText("RS : 0.00");
          lblp3.setText("RS : 0.00");
        lblp1.setText("PHP");
              txtcf.setText("");
        txtcm.setText("");
        txtcid.setText("");
        txtcname.setText("");
         lblc2.setText("RS : 0.00");
          lblc3.setText("RS : 0.00");
        lblc1.setText("C#");
       
            try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
            String newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
            
            lbldate.setText(newdate);
           // jLabel2.setText(ar[3]); 
                    }
                
                }
            }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }

           try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
            String newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
            
            lbldateJ.setText(newdate);
            lbldateA.setText(newdate);
            lbldateP.setText(newdate);
            lbldateC.setText(newdate);
           // jLabel2.setText(ar[3]); 
                    }
                
                }
            }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtadm = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbldate = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbldue = new javax.swing.JLabel();
        lbltotalpay = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lblcourse = new javax.swing.JLabel();
        lbldateJ = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtaid = new javax.swing.JTextField();
        txtaf = new javax.swing.JTextField();
        txtaname = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbla3 = new javax.swing.JLabel();
        lbla2 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbla1 = new javax.swing.JLabel();
        lbldateA = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        txtpf = new javax.swing.JTextField();
        txtpname = new javax.swing.JTextField();
        txtptotal = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        lblp1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblp3 = new javax.swing.JLabel();
        lblp2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbldateP = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        txtcf = new javax.swing.JTextField();
        txtcname = new javax.swing.JTextField();
        txtcm = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        btnclear1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblc3 = new javax.swing.JLabel();
        lblc2 = new javax.swing.JLabel();
        lblc1 = new javax.swing.JLabel();
        lbldateC = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 24));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Student Id : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Admission Fee : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Student Name : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Payment Amount : ");

        txtid.setText("jTextField1");
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtadm.setText("jTextField1");

        txtname.setText("jTextField1");

        txtam.setText("jTextField1");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addpayment.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtadm, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 770, 190));

        lbldate.setForeground(new java.awt.Color(204, 0, 0));
        lbldate.setText("jLabel2");
        jPanel1.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 0));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ho.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 110, 60));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Paid Date", "Paid"
            }
        ));
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 770, 140));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel7.setText("Total Paid Amount : ");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel8.setText("Payment Due : ");

        lbldue.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbldue.setForeground(new java.awt.Color(204, 0, 0));
        lbldue.setText("jLabel10");

        lbltotalpay.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbltotalpay.setText("jLabel10");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldue)
                    .addComponent(lbltotalpay))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbltotalpay))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbldue))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 390, 110));

        jLabel35.setFont(new java.awt.Font("Lucida Fax", 1, 36));
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Student Payment Info");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 500, 40));

        lblcourse.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblcourse.setForeground(new java.awt.Color(255, 255, 255));
        lblcourse.setText("jLabel6");
        jPanel1.add(lblcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, 10));

        lbldateJ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldateJ.setForeground(new java.awt.Color(255, 255, 255));
        lbldateJ.setText("lbldateJ");
        jPanel1.add(lbldateJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1.jpg"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 650));

        jTabbedPane1.addTab("        JAVA        ", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Student Id : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Admission Fee : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Student Name : ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setText("Payment Amount : ");

        txtaid.setText("jTextField1");
        txtaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaidActionPerformed(evt);
            }
        });

        txtaf.setText("jTextField1");

        txtaname.setText("jTextField1");

        txtamount.setText("jTextField1");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addpayment.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(txtaid, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtaf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtaname, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 770, 190));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ho.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 110, 60));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Paid Date", "Paid"
            }
        ));
        jScrollPane2.setViewportView(table2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 770, 140));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel13.setText("Total Paid Amount : ");

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel14.setText("Payment Due : ");

        lbla3.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbla3.setForeground(new java.awt.Color(204, 0, 0));
        lbla3.setText("jLabel10");

        lbla2.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbla2.setText("jLabel10");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbla3)
                    .addComponent(lbla2))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbla2)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lbla3))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 390, 110));

        jLabel34.setFont(new java.awt.Font("Lucida Fax", 1, 36));
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Student Payment Info");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 500, 40));

        lbla1.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbla1.setForeground(new java.awt.Color(255, 255, 255));
        lbla1.setText("jLabel6");
        jPanel2.add(lbla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, 20));

        lbldateA.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbldateA.setForeground(new java.awt.Color(255, 255, 255));
        lbldateA.setText("lbldateA");
        jPanel2.add(lbldateA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1.jpg"))); // NOI18N
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 650));

        jTabbedPane1.addTab("      ANDROID       ", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel15.setText("Student Id : ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel16.setText("Admission Fee : ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel17.setText("Student Name : ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel18.setText("Payment Amount : ");

        txtpid.setText("jTextField1");
        txtpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpidActionPerformed(evt);
            }
        });

        txtpf.setText("jTextField1");

        txtpname.setText("jTextField1");

        txtptotal.setText("jTextField1");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addpayment.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.jpg"))); // NOI18N
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtptotal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtptotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnclear, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 770, 190));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ho.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 110, 60));

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Paid Date", "Paid"
            }
        ));
        jScrollPane3.setViewportView(table3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 770, 140));

        lblp1.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblp1.setForeground(new java.awt.Color(255, 255, 255));
        lblp1.setText("jLabel6");
        jPanel3.add(lblp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, 10));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel20.setText("Total Paid Amount : ");

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel21.setText("Payment Due : ");

        lblp3.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblp3.setForeground(new java.awt.Color(204, 0, 0));
        lblp3.setText("jLabel10");

        lblp2.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblp2.setText("jLabel10");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblp3)
                    .addComponent(lblp2))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblp2))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblp3))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 390, 110));

        jLabel33.setFont(new java.awt.Font("Lucida Fax", 1, 36));
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Student Payment Info");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 500, 40));

        lbldateP.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbldateP.setForeground(new java.awt.Color(255, 255, 255));
        lbldateP.setText("lbldateP");
        jPanel3.add(lbldateP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1.jpg"))); // NOI18N
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 650));

        jTabbedPane1.addTab("          PHP          ", jPanel3);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel22.setText("Student Id : ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel23.setText("Admission Fee : ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel24.setText("Student Name : ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel25.setText("Payment Amount : ");

        txtcid.setText("jTextField1");
        txtcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcidActionPerformed(evt);
            }
        });

        txtcf.setText("jTextField1");

        txtcname.setText("jTextField1");

        txtcm.setText("jTextField1");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addpayment.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnclear1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.jpg"))); // NOI18N
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(39, 39, 39)
                        .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtcname, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtcm, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtcf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnclear1, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 770, 190));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ho.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 110, 60));

        jLabel26.setFont(new java.awt.Font("Lucida Fax", 1, 36));
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Student Payment Info");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 500, 40));

        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Paid Date", "Paid"
            }
        ));
        jScrollPane4.setViewportView(table4);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 770, 140));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel27.setText("Total Paid Amount : ");

        jLabel28.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel28.setText("Payment Due : ");

        lblc3.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblc3.setForeground(new java.awt.Color(204, 0, 0));
        lblc3.setText("jLabel10");

        lblc2.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblc2.setText("jLabel10");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(33, 33, 33)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblc3)
                    .addComponent(lblc2))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblc2))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblc3))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 390, 110));

        lblc1.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblc1.setForeground(new java.awt.Color(255, 255, 255));
        lblc1.setText("jLabel6");
        jPanel8.add(lblc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, 20));

        lbldateC.setBackground(new java.awt.Color(0, 0, 0));
        lbldateC.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbldateC.setForeground(new java.awt.Color(255, 255, 255));
        lbldateC.setText("lbldateC");
        jPanel8.add(lbldateC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1.jpg"))); // NOI18N
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 650));

        jTabbedPane1.addTab("          C#          ", jPanel8);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 630));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-846)/2, (screenSize.height-670)/2, 846, 670);
    }// </editor-fold>//GEN-END:initComponents

private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
// TODO add your handling code here:
    
    try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM payment WHERE SID='"+txtid.getText()+"' AND course='"+lblcourse.getText()+"'");
             
             while(rs.next()){
             
                txtname.setText(rs.getString("name"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
       try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM admission WHERE SID='"+txtid.getText()+"'");
             
             while(rs.next()){
             
                txtadm.setText(rs.getString("fee"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    double total=0;
    String am;
    double paid;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtid.getText()+"' AND course='"+lblcourse.getText()+"'");
             
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table1.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
                
               am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
        lbltotalpay.setText("RS ."+total);
         double t=10000;
         double due=t-total;
         lbldue.setText("RS ."+due);
         
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtidActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    
       DefaultTableModel aj=(DefaultTableModel)table1.getModel();
    
    while(aj.getRowCount() > 0){
    
        for(int i=0;i<aj.getRowCount();i++){
            aj.removeRow(i);
        }
    }
       
       
    
    try {
       
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        s.executeUpdate("UPDATE admission SET fee='"+txtadm.getText()+"' WHERE sid='"+txtid.getText()+"'");
        
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    try {
         Connection c1=DB.mycon();
        Statement s1=c1.createStatement();
        s1.executeUpdate("INSERT INTO `payment`( `sid`, `name`, `course`, `amount`, `datet`) VALUES ('"+txtid.getText()+"','"+txtname.getText()+"','"+lblcourse.getText()+"','"+txtam.getText()+"','"+lbldateJ.getText()+"')");
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
     double total=0;
    String am;
    double paid;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtid.getText()+"' AND course='"+lblcourse.getText()+"'");
             
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table1.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
                
               am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
        lbltotalpay.setText("RS ."+total);
         double t=10000;
         double due=t-total;
         lbldue.setText("RS ."+due);
         
    } catch (Exception e) {
        e.printStackTrace();
    }
    JOptionPane.showMessageDialog(txtamount, "Sucssesfully Added...");
    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    txtadm.setText("");
    txtam.setText("");
    txtid.setText("");
    txtname.setText("");
 lbldue.setText("RS : 0.00");
          lbltotalpay.setText("RS : 0.00");
    DefaultTableModel a=(DefaultTableModel)table1.getModel();
    
    while(a.getRowCount() > 0){
    
        for(int i=0;i<a.getRowCount();i++){
            a.removeRow(i);
        }
    }
    
    
    txtid.grabFocus();
}//GEN-LAST:event_jButton2ActionPerformed

private void txtpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpidActionPerformed
// TODO add your handling code here:
    lblp1.setText("PHP");
    try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM payment WHERE SID='"+txtpid.getText()+"' AND course='"+lblp1.getText()+"'");
             
             while(rs.next()){
             
                txtpname.setText(rs.getString("name"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
       try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM admission WHERE SID='"+txtpid.getText()+"'");
             
             while(rs.next()){
             
                txtpf.setText(rs.getString("fee"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
        double total=0;
    String am;
    double paid;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtpid.getText()+"' AND course='"+lblp1.getText()+"'");
             
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table3.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
             
                                
               am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
        lblp2.setText("RS ."+total);
          double t=10000;
         double due=t-total;
         lblp3.setText("RS ."+due);       
             
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtpidActionPerformed

private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
// TODO add your handling code here:
    txtpf.setText("");
    txtptotal.setText("");
    txtpid.setText("");
    txtpname.setText("");
          lblp2.setText("RS : 0.00");
          lblp3.setText("RS : 0.00");
          
     DefaultTableModel a=(DefaultTableModel)table3.getModel();
    
    while(a.getRowCount() > 0){
    
        for(int i=0;i<a.getRowCount();i++){
            a.removeRow(i);
        }
    }
    
    txtpid.grabFocus();
}//GEN-LAST:event_btnclearActionPerformed

private void txtcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcidActionPerformed
// TODO add your handling code here:
    lblc1.setText("C#");
    try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM payment WHERE SID='"+txtcid.getText()+"' AND course='"+lblc1.getText()+"'");
             
             while(rs.next()){
             
                txtcname.setText(rs.getString("name"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
       try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM admission WHERE SID='"+txtcid.getText()+"'");
             
             while(rs.next()){
             
                txtcf.setText(rs.getString("fee"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
         double total=0;
    String am;
    double paid;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtcid.getText()+"' AND course='"+lblc1.getText()+"'");
             
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table4.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
             
                      am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
        lblc2.setText("RS ."+total);
         double t=10000;
         double due=t-total;
         lblc3.setText("RS ."+due);
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtcidActionPerformed

private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
// TODO add your handling code here:
    txtcf.setText("");
    txtcm.setText("");
    txtcid.setText("");
    txtcname.setText("");
         lblc2.setText("RS : 0.00");
          lblc3.setText("RS : 0.00");
     DefaultTableModel a=(DefaultTableModel)table4.getModel();
    
    while(a.getRowCount() > 0){
    
        for(int i=0;i<a.getRowCount();i++){
            a.removeRow(i);
        }
    }
    
    txtcid.grabFocus();
}//GEN-LAST:event_btnclear1ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    
         
      
       DefaultTableModel aA=(DefaultTableModel)table3.getModel();
    
    while(aA.getRowCount() > 0){
    
        for(int i=0;i<aA.getRowCount();i++){
            aA.removeRow(i);
        }
    }
       
       
    
    try {
       
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        s.executeUpdate("UPDATE admission SET fee='"+txtpf.getText()+"' WHERE sid='"+txtpid.getText()+"'");
        
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    try {
         Connection c1=DB.mycon();
        Statement s1=c1.createStatement();
        s1.executeUpdate("INSERT INTO `payment`( `sid`, `name`, `course`, `amount`, `datet`) VALUES ('"+txtpid.getText()+"','"+txtpname.getText()+"','"+lblp1.getText()+"','"+txtptotal.getText()+"','"+lbldateP.getText()+"')");
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
     double total=0;
    String am;
    double paid;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtpid.getText()+"' AND course='"+lblp1.getText()+"'");
             
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table3.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
                
               am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
        lblp2.setText("RS ."+total);
         double t=10000;
         double due=t-total;
         lblp3.setText("RS ."+due);
         
    } catch (Exception e) {
        e.printStackTrace();
    }
    JOptionPane.showMessageDialog(txtamount, "Sucssesfully Added...");
    
    
    
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    
             
      
       DefaultTableModel aA=(DefaultTableModel)table4.getModel();
    
    while(aA.getRowCount() > 0){
    
        for(int i=0;i<aA.getRowCount();i++){
            aA.removeRow(i);
        }
    }
       
       
    
    try {
       
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        s.executeUpdate("UPDATE admission SET fee='"+txtcf.getText()+"' WHERE sid='"+txtcid.getText()+"'");
        
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    try {
         Connection c1=DB.mycon();
        Statement s1=c1.createStatement();
        s1.executeUpdate("INSERT INTO `payment`( `sid`, `name`, `course`, `amount`, `datet`) VALUES ('"+txtcid.getText()+"','"+txtcname.getText()+"','"+lblc1.getText()+"','"+txtcm.getText()+"','"+lbldateC.getText()+"')");
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
     double total=0;
    String am;
    double paid;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtcid.getText()+"' AND course='"+lblc1.getText()+"'");
             
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table4.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
                
               am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
        lblc2.setText("RS ."+total);
         double t=10000;
         double due=t-total;
         lblc3.setText("RS ."+due);
         
    } catch (Exception e) {
        e.printStackTrace();
    }
    JOptionPane.showMessageDialog(txtamount, "Sucssesfully Added...");
    
    
    
    
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
    new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// TODO add your handling code here:
    new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton9ActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
// TODO add your handling code here:
    new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton10ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    txtaf.setText("");
    txtamount.setText("");
    txtaid.setText("");
    txtaname.setText("");
         lbla2.setText("RS : 0.00");
          lbla3.setText("RS : 0.00");
      DefaultTableModel a=(DefaultTableModel)table2.getModel();
    
    while(a.getRowCount() > 0){
    
        for(int i=0;i<a.getRowCount();i++){
            a.removeRow(i);
        }
    }
    
    txtaid.grabFocus();
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
     
      
       DefaultTableModel aA=(DefaultTableModel)table2.getModel();
    
    while(aA.getRowCount() > 0){
    
        for(int i=0;i<aA.getRowCount();i++){
            aA.removeRow(i);
        }
    }
       
       
    
    try {
       
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        s.executeUpdate("UPDATE admission SET fee='"+txtaf.getText()+"' WHERE sid='"+txtaid.getText()+"'");
        
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    try {
         Connection c1=DB.mycon();
        Statement s1=c1.createStatement();
        s1.executeUpdate("INSERT INTO `payment`( `sid`, `name`, `course`, `amount`, `datet`) VALUES ('"+txtaid.getText()+"','"+txtaname.getText()+"','"+lbla1.getText()+"','"+txtamount.getText()+"','"+lbldateA.getText()+"')");
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
     double total=0;
    String am;
    double paid;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtaid.getText()+"' AND course='"+lbla1.getText()+"'");
             
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table2.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
                
               am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
        lbla2.setText("RS ."+total);
         double t=10000;
         double due=t-total;
         lbla3.setText("RS ."+due);
         
    } catch (Exception e) {
        e.printStackTrace();
    }
    JOptionPane.showMessageDialog(txtamount, "Sucssesfully Added...");
}//GEN-LAST:event_jButton3ActionPerformed

private void txtaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaidActionPerformed
// TODO add your handling code here:
     lbla1.setText("ANDROID");
    try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM payment WHERE SID='"+txtaid.getText()+"' AND course='"+lbla1.getText()+"'");
             
             while(rs.next()){
             
                txtaname.setText(rs.getString("name"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
       try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM admission WHERE SID='"+txtaid.getText()+"'");
             
             while(rs.next()){
             
                txtaf.setText(rs.getString("fee"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    lbla1.setText("ANDROID");
    double total=0;
    String am;
    double paid;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtaid.getText()+"' AND course='"+lbla1.getText()+"'");
             
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table2.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
                
               am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
        lbla2.setText("RS ."+total);
         double t=10000;
         double due=t-total;
         lbla3.setText("RS ."+due);
         
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtaidActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  try {
                    UIManager.setLookAndFeel(new GraphiteLookAndFeel());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new paymentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclear1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbla1;
    private javax.swing.JLabel lbla2;
    private javax.swing.JLabel lbla3;
    private javax.swing.JLabel lblc1;
    private javax.swing.JLabel lblc2;
    private javax.swing.JLabel lblc3;
    private javax.swing.JLabel lblcourse;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldateA;
    private javax.swing.JLabel lbldateC;
    private javax.swing.JLabel lbldateJ;
    private javax.swing.JLabel lbldateP;
    private javax.swing.JLabel lbldue;
    private javax.swing.JLabel lblp1;
    private javax.swing.JLabel lblp2;
    private javax.swing.JLabel lblp3;
    private javax.swing.JLabel lbltotalpay;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTable table4;
    private javax.swing.JTextField txtadm;
    private javax.swing.JTextField txtaf;
    private javax.swing.JTextField txtaid;
    private javax.swing.JTextField txtam;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtaname;
    private javax.swing.JTextField txtcf;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcm;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpf;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtptotal;
    // End of variables declaration//GEN-END:variables

}
