/*
 * payment.java
 *
 * Created on December 12, 2016, 12:31 PM
 */

package aitec1;

import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import java.sql.Connection;
import java.sql.ResultSet;

import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  User
 */
public class studentPayment extends javax.swing.JFrame {
double price;
 String mo;   
     public studentPayment() {
    
     initComponents();
     
             
              txtadm.setText("");
        txtam.setText("");
        txtid.setText("");
        txtname.setText("");
         lbldue.setText("RS : 0.00");
          lbltotalpay.setText("RS : 0.00");
     
     
    
    }
    /** Creates new form payment */
    public studentPayment(String course) {
        initComponents();
        lblCourse.setText(course);
        
        
              txtadm.setText("");
        txtam.setText("");
        txtid.setText("");
        txtname.setText("");
         lbldue.setText("RS : 0.00");
          lbltotalpay.setText("RS : 0.00");
          
              try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
            String m=ar[1];
            
            if(m.equals("Dec")){
            
                mo="12";
            }
            String newdate=ar[5]+"-"+mo+"-"+ar[2];
            
            lbldateJ.setText(newdate);
           
           // jLabel2.setText(ar[3]); 
                    }
                
                }
            }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       


     
        /*    try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
            String newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
            
            lbldate.setText(newdate);
           // jLabel2.setText(ar[3]); 
                    }
                
                }
            }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       */ 
        
    }
    
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtadm = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbldue = new javax.swing.JLabel();
        lbltotalpay = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        lblCourse = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbldateJ = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Student Id : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Admission Fee : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Student Name : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Payment Amount : ");

        txtid.setText("jTextField1");
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtadm.setText("jTextField1");

        txtname.setText("jTextField1");

        txtam.setText("jTextField1");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addpayment.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtadm, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 770, 260));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Paid Date", "Paid"
            }
        ));
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 780, 130));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel7.setText("Total Paid Amount : ");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18));
        jLabel8.setText("Payment Due : ");

        lbldue.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbldue.setForeground(new java.awt.Color(204, 0, 0));
        lbldue.setText("jLabel10");

        lbltotalpay.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbltotalpay.setText("jLabel10");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldue)
                    .addComponent(lbltotalpay))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbltotalpay))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbldue))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 390, 110));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ho.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 110, 60));

        lblCourse.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblCourse.setForeground(new java.awt.Color(204, 0, 0));
        lblCourse.setText("jLabel1");
        getContentPane().add(lblCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        jLabel35.setFont(new java.awt.Font("Lucida Fax", 1, 36));
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Student Payment Info");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 500, 40));

        lbldateJ.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbldateJ.setForeground(new java.awt.Color(255, 255, 255));
        lbldateJ.setText("lbldateJ");
        getContentPane().add(lbldateJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1.jpg"))); // NOI18N
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 650));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-846)/2, (screenSize.height-670)/2, 846, 670);
    }// </editor-fold>//GEN-END:initComponents

private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
// TODO add your handling code here:
    
    try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM payment WHERE SID='"+txtid.getText()+"' AND course='"+lblCourse.getText()+"'");
             
             while(rs.next()){
             
                txtname.setText(rs.getString("name"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
       try {
        Connection c=DB.mycon();
             Statement s=c.createStatement();
             ResultSet rs=s.executeQuery("SELECT * FROM admission WHERE SID='"+txtid.getText()+"'");
             
             while(rs.next()){
             
                txtadm.setText(rs.getString("fee"));
             }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    double total=0;
    String am;
    double paid;
    
    String p;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtid.getText()+"' AND course='"+lblCourse.getText()+"'");
             
             Connection c2=DB.mycon();
             Statement s2=c2.createStatement();
             ResultSet rs2=s2.executeQuery("SELECT * FROM `course` WHERE name='"+lblCourse.getText()+"'");
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table1.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
               
               am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
             while(rs2.next()){
             
                    p=rs2.getString("fee");
                    price=Double.parseDouble(p);
             }
             
             
        lbltotalpay.setText("RS ."+total);
        
         double due=price-total;
         lbldue.setText("RS ."+due);
         
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtidActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    
       DefaultTableModel aj=(DefaultTableModel)table1.getModel();
    
    while(aj.getRowCount() > 0){
    
        for(int i=0;i<aj.getRowCount();i++){
            aj.removeRow(i);
        }
    }
       
     int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to add this payment??");
     
     if(x==0){
    
    try {
       
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        s.executeUpdate("UPDATE admission SET fee='"+txtadm.getText()+"' WHERE sid='"+txtid.getText()+"'");
        
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    try {
         Connection c1=DB.mycon();
        Statement s1=c1.createStatement();
        s1.executeUpdate("INSERT INTO `payment`( `sid`, `name`, `course`, `amount`, `datet`) VALUES ('"+txtid.getText()+"','"+txtname.getText()+"','"+lblCourse.getText()+"','"+txtam.getText()+"','"+lbldateJ.getText()+"')");
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
     double total=0;
    String am;
    double paid;
      try {
        Connection c1=DB.mycon();
             Statement s1=c1.createStatement();
             ResultSet rs1=s1.executeQuery("SELECT * FROM payment WHERE SID='"+txtid.getText()+"' AND course='"+lblCourse.getText()+"'");
             
             while(rs1.next()){
             
                DefaultTableModel a=(DefaultTableModel)table1.getModel();
                a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
                
               am =rs1.getString("amount");
                paid=Double.parseDouble(am);
                total=total+paid;
             }
        lbltotalpay.setText("RS ."+total);
         double t=10000;
         double due=t-total;
         lbldue.setText("RS ."+due);
         
    } catch (Exception e) {
        e.printStackTrace();
    }
    JOptionPane.showMessageDialog(rootPane, "Sussucefully Saved the Payment..");
    
     }
     else if(x==1){
     
                txtadm.setText("");
    txtam.setText("");
    txtid.setText("");
    txtname.setText("");
 lbldue.setText("RS : 0.00");
          lbltotalpay.setText("RS : 0.00");
    DefaultTableModel a=(DefaultTableModel)table1.getModel();
    
    while(a.getRowCount() > 0){
    
        for(int i=0;i<a.getRowCount();i++){
            a.removeRow(i);
        }
    }
    
    
    txtid.grabFocus();
     
     }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    txtadm.setText("");
    txtam.setText("");
    txtid.setText("");
    txtname.setText("");
 lbldue.setText("RS : 0.00");
          lbltotalpay.setText("RS : 0.00");
    DefaultTableModel a=(DefaultTableModel)table1.getModel();
    
    while(a.getRowCount() > 0){
    
        for(int i=0;i<a.getRowCount();i++){
            a.removeRow(i);
        }
    }
    
    
    txtid.grabFocus();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  try {
                    UIManager.setLookAndFeel(new GraphiteLookAndFeel());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new studentPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldateJ;
    private javax.swing.JLabel lbldue;
    private javax.swing.JLabel lbltotalpay;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtadm;
    private javax.swing.JTextField txtam;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
