/*
 * payment.java
 *
 * Created on December 12, 2016, 12:31 PM
 */

package aitec1;

import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import java.sql.Connection;
import java.sql.ResultSet;

import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  User
 */
public class studentDetails extends javax.swing.JFrame {

    
    String id1,name;
    /** Creates new form payment */
    public studentDetails() {
        initComponents();

        try {
            
            Connection c=DB.mycon();
            Statement s=c.createStatement();
            ResultSet rs=s.executeQuery("SELECT * FROM `students` WHERE 1");
            
            while(rs.next()){
            
            //  DefaultTableModel a=(DefaultTableModel)table3.getModel();
              //  a.addRow(new Object[] {rs1.getString("sid"),rs1.getString("name"),rs1.getString("datet"),rs1.getString("amount")});
                
                String id=rs.getString("sid");
                cId.addItem(id);
                
                String name=rs.getString("name");
                cName.addItem(name);
                
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        /*    try {
            
         new Thread(new Runnable() {

                public void run() {
                   
                    while(true){
                          Date d=new Date();
            String date=d.toString();
            String ar[]=date.split(" ");
            String newdate=ar[5]+"-"+ar[1]+"-"+ar[2];
            
            lbldate.setText(newdate);
           // jLabel2.setText(ar[3]); 
                    }
                
                }
            }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       */ 
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cName = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        cId = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cName.setFont(new java.awt.Font("Tahoma", 1, 12));
        cName.setForeground(new java.awt.Color(204, 0, 51));
        cName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select student name" }));
        getContentPane().add(cName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 240, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Student ID : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Aparajita", 1, 36));
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("AiTEC");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ho.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 110, 60));

        cId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cId.setForeground(new java.awt.Color(255, 0, 51));
        cId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select the Student ID" }));
        getContentPane().add(cId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 240, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Name : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        table1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        table1.setFont(new java.awt.Font("Tahoma", 1, 12));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Date", "Name", "Address", "BirthDay", "Institute", "Telephone", "E-mail"
            }
        ));
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 730, 150));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SEA.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 110, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SEARCH STUDENTS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 650));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-846)/2, (screenSize.height-670)/2, 846, 670);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
  
    try {
        
 
    
        
        Connection c=DB.mycon();
        Statement s=c.createStatement();
        
        ResultSet rs=s.executeQuery("SELECT * FROM students WHERE sid='"+cId.getSelectedItem().toString()+"' OR name='"+cName.getSelectedItem().toString()+"'");
        
                       DefaultTableModel a1=(DefaultTableModel)table1.getModel();
    
    while(a1.getRowCount() > 0){
    
        for(int i=0;i<a1.getRowCount();i++){
            a1.removeRow(i);
        }
    }
        while(rs.next()){
        
            id1=rs.getString("sid").toString();
            name=rs.getString("name");
                DefaultTableModel a=(DefaultTableModel)table1.getModel();
                a.addRow(new Object[] {rs.getString("sid"),rs.getString("date"),rs.getString("name"),rs.getString("address"),rs.getString("birthday"),rs.getString("institute"),rs.getString("tel"),rs.getString("email")});
        
        }
                       cId.setSelectedIndex(0);
                       cName.setSelectedIndex(0);
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    new home().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  try {
                    UIManager.setLookAndFeel(new GraphiteLookAndFeel());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new studentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cId;
    private javax.swing.JComboBox cName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables

}
